# -*- coding: ascii -*-
# Dump SoftMotion configuration (axis group, kinematics, axes) to a YAML
# snapshot under doc/softmotion_snapshot.yaml. Run periodically and commit
# the snapshot so kinematic / axis-group changes show up in git diffs.
#
# Why: SoftMotion config (SpiderR kinematic chain, axis modulo settings,
# scaling factors) lives entirely inside the binary CODESYS project file.
# Without a snapshot, changes are invisible to code review and rollback.
# This dump is best-effort - it captures what the scripting API exposes,
# not the full project state.

import os
import json

proj = projects.primary

REPO_ROOT = r"c:\Users\X1\Desktop\X2.5\TCP_UI\TCP_UI"
OUT_PATH = os.path.join(REPO_ROOT, "doc", "softmotion_snapshot.yaml")


def safe_name(o):
    try: return o.get_name()
    except Exception: return "?"


def safe_type(o):
    try: return str(o.type)
    except Exception:
        try: return type(o).__name__
        except Exception: return "?"


def deep(o, d=0, max_d=10):
    if d > max_d: return
    yield o, d
    try:
        for c in o.get_children():
            for x, dd in deep(c, d + 1, max_d): yield x, dd
    except Exception:
        pass


def get_text(o, attr):
    try:
        v = getattr(o, attr, None)
        return getattr(v, "text", None) if v is not None else None
    except Exception:
        return None


def dump_obj_attrs(o):
    """Best-effort attribute dump — most SoftMotion config objects don't
    expose readable attributes via the public scripting API, so this
    is mostly empty. We capture what we can."""
    out = {}
    try:
        for k in dir(o):
            if k.startswith("_"): continue
            try:
                v = getattr(o, k)
                if callable(v): continue
                s = repr(v)
                if len(s) > 300: s = s[:300] + "..."
                # Filter out boilerplate
                if k in ("get_name", "get_children", "type"): continue
                out[k] = s
            except Exception:
                pass
    except Exception:
        pass
    return out


# --------------------------------------------------------------- collect ----

snapshot = {
    "_note": "Best-effort SoftMotion config snapshot. Generated by dump_softmotion_config.py.",
    "axis_groups": [],
    "axis_pool": [],
    "ethercat_axes": [],
}

device = None
for top in proj.get_children():
    if safe_name(top) == "Device":
        device = top
        break

# Walk Application for axis-group nodes (SpiderR-style)
if device:
    for c in device.get_children():
        if safe_name(c) == "Plc Logic":
            for app in c.get_children():
                if safe_name(app) == "Application":
                    for ch in app.get_children():
                        # Axis-group objects use a specific type GUID
                        # (940a539a-1dd2-4c8f-8499-17a4a93be9bd for SpiderR).
                        ty = safe_type(ch)
                        nm = safe_name(ch)
                        # Heuristic: axis groups are usually NonTextualObject
                        # with no children but recognizable name. Capture anything
                        # that smells like a kinematic / motion node.
                        if ("940a539a" in ty or
                            any(s in nm.lower() for s in
                                ("spider", "trafo", "kin", "axisgroup"))):
                            snapshot["axis_groups"].append({
                                "name": nm,
                                "type_guid": ty,
                                "attrs": dump_obj_attrs(ch),
                            })

    # SoftMotion General Axis Pool
    for c in device.get_children():
        if safe_name(c) == "SoftMotion General Axis Pool":
            for ax in c.get_children():
                snapshot["axis_pool"].append({
                    "name": safe_name(ax),
                    "type_guid": safe_type(ax),
                    "attrs": dump_obj_attrs(ax),
                })

    # EtherCAT axes (drive children)
    for c in device.get_children():
        if safe_name(c) == "EtherCAT_Master_SoftMotion":
            for drv in c.get_children():
                drv_entry = {
                    "drive": safe_name(drv),
                    "drive_type": safe_type(drv),
                    "axes": [],
                }
                for ax in (drv.get_children() if hasattr(drv, "get_children") else []):
                    drv_entry["axes"].append({
                        "name": safe_name(ax),
                        "type_guid": safe_type(ax),
                        "attrs": dump_obj_attrs(ax),
                    })
                snapshot["ethercat_axes"].append(drv_entry)

# Also try to capture AxisGroupManager FB declaration (this DOES have
# textual_declaration, unlike the SpiderR object).
for top in proj.get_children():
    for o, _ in deep(top, max_d=10):
        nm = safe_name(o)
        if nm in ("AxisGroupManager", "AxisGroupSM"):
            decl = get_text(o, "textual_declaration")
            if decl:
                snapshot.setdefault("manager_declarations", {})[nm] = {
                    "decl_lines": len(decl.splitlines()),
                    "decl_first_80": "\n".join(decl.splitlines()[:80]),
                }


# ---------------------------------------------------------------- write ----

def to_yaml(obj, indent=0):
    pad = "  " * indent
    out = []
    if isinstance(obj, dict):
        if not obj:
            return "{}"
        for k, v in obj.items():
            ks = str(k)
            if isinstance(v, (dict, list)) and v:
                out.append("{}{}:".format(pad, ks))
                out.append(to_yaml(v, indent + 1))
            else:
                vs = to_yaml(v, indent + 1)
                if isinstance(v, str) and ("\n" in v or len(v) > 80):
                    out.append("{}{}: |".format(pad, ks))
                    for line in v.splitlines():
                        out.append("  " * (indent + 1) + line)
                else:
                    out.append("{}{}: {}".format(pad, ks, vs))
    elif isinstance(obj, list):
        if not obj:
            return "[]"
        for item in obj:
            if isinstance(item, (dict, list)):
                out.append("{}-".format(pad))
                out.append(to_yaml(item, indent + 1))
            else:
                out.append("{}- {}".format(pad, to_yaml(item, indent + 1)))
    elif isinstance(obj, bool):
        return "true" if obj else "false"
    elif obj is None:
        return "null"
    elif isinstance(obj, (int, float)):
        return str(obj)
    else:
        s = str(obj)
        # Escape if contains special yaml chars
        if any(c in s for c in ":#[]{},&*!|>%@`'\""):
            s = '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
        return s
    return "\n".join(out)


yaml_text = to_yaml(snapshot)

with open(OUT_PATH, "w") as f:
    f.write(yaml_text)
    f.write("\n")

print("wrote:", OUT_PATH)
print("axis_groups:", len(snapshot["axis_groups"]))
print("axis_pool:",   len(snapshot["axis_pool"]))
print("ethercat_axes:", sum(len(d["axes"]) for d in snapshot["ethercat_axes"]))
