{attribute 'to_string'}
TYPE E_RobotEvent :
(
    EV_NONE,        // No event, default state
    EV_BOOT,        // No event, default state
	EV_POWER_ON,
	EV_POWER_OFF,
    EV_GROUP_ENABLE,      // Event to start the enabling sequence
    EV_GROUP_DISABLE,      // Event to start the enabling sequence
	
    EV_HOME_GO,        // Event to trigger the homing sequence
    EV_HOME_GO_FORCE_SKIP,        // Event to trigger the homing sequence
	
    EV_RESET,       // Event to reset a latched error
	EV_ERROR,
	
	EV_OK,
	EV_ER
) UDINT; 
END_TYPE